services:

  mongo:
    image: mongo
    container_name: mongo-container
    ports:
      - 27018:27017
    volumes:
      - './docker/mongodb:/data/db'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: mongoose0215

# COMMANDS
# docker-compose -f docker-compose.yml up --detach
# docker-compose -f docker-compose.yml down
